apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-infer
  labels:
    app: aci-infer
spec:
  selector:
    matchLabels:
      app: aci-infer
  template:
    metadata:
      labels:
        app: aci-infer
    spec:
      containers:
      - name: aci-infer
        image: xcreuwcontainers.azurecr.io/infer:v1.0
        env:
        - name: SERVICEBUS_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: infer
              key: SERVICEBUS_NAMESPACE

        - name: SERVICEBUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: infer
              key: SERVICEBUS_CONNECTION_STRING

        - name: SERVICEBUS_ACCESSKEY_NAME
          valueFrom:
            secretKeyRef:
              name: infer
              key: SERVICEBUS_ACCESSKEY_NAME

        - name: SERVICEBUS_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: infer
              key: SERVICEBUS_ACCESSKEY

        - name: STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: infer
              key: STORAGE_ACCOUNT

        - name: STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: infer
              key: STORAGE_KEY
        
        - name: MONGODB
          valueFrom:
            secretKeyRef:
              name: infer
              key: MONGODB

        resources:
          requests:
            cpu: 4
            memory: 14G
      imagePullSecrets:
      - name: acr-auth
      nodeSelector:
        kubernetes.io/hostname: virtual-kubelet-virtual-kubelet-linux-westeurope
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Equal
        value: azure
        effect: NoSchedule

---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: aci-infer-scaler
  labels:
    app: aci-infer
    deploymentName: aci-infer
spec:
  scaleTargetRef:
    deploymentName: aci-infer
  pollingInterval: 5
  cooldownPeriod:  10
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: cocoonaks
      connection: SERVICEBUS_CONNECTION_STRING
      queueLength: '100'